//Plot tracking data for the mothers and daughters in the dataset
//The required format is as generated by the Manual Tracking plugin 
//http://rsbweb.nih.gov/ij/plugins/track/track.html
//assuming Results table column headings: Track > Slice > X > Y

//get the track numbers in an array to use as the index
track_number = list_no_repeats ("Results", "Track");

//get number of tracks (Track)
Track = track_number.length;

//add a daughter column to the resutls table
		for (i=0; i<nResults; i++) {
			if (getResult("Mother?", i) == 0) {
				setResult("Daughter?", i, 1);		
			}
		}
//get a ist of the mothers to use as an index
mother_numbers = list_no_repeats_skip ("Results", "Track", "Daughter?");//skip daughter

//get number of mother tracks (Track)
Track = track_number.length;

Array.print(track_number);
Array.print(mother_numbers);
//exit();

//Work though the data a track at a time

for (i=0; i<mother_numbers.length; i++){

//Plot the graph
Plot.create("Mother "+mother_numbers[i]+" + daughters a + b", "X", "Y");
//You may want to determine your own limits in some way here
Plot.setLimits(-256, 256, -256, 256);

//does the mother have two daughter?
	var done = false; // used to prematurely terminate loop
	for (j=0; j<track_number.length && !done; j++) {
		print(mother_numbers[i]+"a");
		if (mother_numbers[i]+"a" == track_number[j]) {
			done = true;
		} else {}
	}
	var done1 = false; // used to prematurely terminate loop
	for (j=0; j<track_number.length && !done1; j++) {
		print(mother_numbers[i]+"b");
		if (mother_numbers[i]+"b" == track_number[j]) {
			done1 = true;
		} else {}
	}

	if (done == false || done1 == false) {
		print("Skipping Mother "+mother_numbers[i]);
		} else {

//then get the coordinates of mother and daughter

//get the x, y values in an array
	m_values_x = newArray();
	m_values_y = newArray();
	a_values_x = newArray();
	a_values_y = newArray();
	b_values_x = newArray();
	b_values_y = newArray();

//get the mother coordinates
	for (k=0; k<nResults; k++) {

		if (getResultString("Track", k) == toString(mother_numbers[i])){
			frames = Array.concat(frames, getResult("Frame", k));
			//positions = Array.concat(positions, k);
			x_val = getResult("X", k);
			m_values_x = Array.concat(m_values_x, x_val);
			y_val = getResult("Y", k);
			m_values_y = Array.concat(m_values_y, y_val);
			}
		}
//get daughter a coordinates
	for (l=0; l<nResults; l++) {

		if (getResultString("Track", l) == toString(mother_numbers[i]+"a")){
			//frames = Array.concat(frames, getResult("Frame", l));
			//positions = Array.concat(positions, l);
			x_val = getResult("X", l);
			a_values_x = Array.concat(a_values_x, x_val);
			y_val = getResult("Y", l);
			a_values_y = Array.concat(a_values_y, y_val);
			}
		}
//get daughter b coordinates
	for (m=0; m<nResults; m++) {

		if (getResultString("Track", m) == toString(mother_numbers[i]+"b")){
			//frames = Array.concat(frames, getResult("Frame", m));
			//positions = Array.concat(positions, m);
			x_val = getResult("X", m);
			b_values_x = Array.concat(b_values_x, x_val);
			y_val = getResult("Y", m);
			b_values_y = Array.concat(b_values_y, y_val);
			}
		}

//zero the data
		//get first x and y value
		m_x_0 = m_values_x[0];
		m_y_0 = m_values_y[0];

//mothers need to be reversed
		m_values_x = Array.reverse(m_values_x);
		m_values_y = Array.reverse(m_values_y);
		for (n=0; n<m_values_x.length; n++) {
			addToArray((m_values_x[n]-m_x_0), m_values_x, n);	
			addToArray((m_values_y[n]-m_y_0), m_values_y, n);	
		}
		m_values_x = Array.reverse(m_values_x);
		m_values_y = Array.reverse(m_values_y);

//get first x and y value
		a_x_0 = a_values_x[0];
		a_y_0 = a_values_y[0];

//daughters don't
		for (n=0; n<a_values_x.length; n++) {
			addToArray((a_values_x[n]-a_x_0), a_values_x, n);	
			addToArray((a_values_y[n]-a_y_0), a_values_y, n);	
		}

//get first x and y value
		b_x_0 = b_values_x[0];
		b_y_0 = b_values_y[0];

//daughters don't
		for (n=0; n<b_values_x.length; n++) {
			addToArray((b_values_x[n]-b_x_0), b_values_x, n);	
			addToArray((b_values_y[n]-b_y_0), b_values_y, n);	
		}

	//Plot each track       
        Plot.setColor("black");
        Plot.setLineWidth(2);
        Plot.add("lines", m_values_x, m_values_y);
        Plot.add("circles", m_values_x, m_values_y);
        Plot.setColor("blue");
        Plot.setLineWidth(2);
        Plot.add("lines", a_values_x, a_values_y);
        Plot.add("circles", a_values_x, a_values_y);
        Plot.setColor("red");
        Plot.setLineWidth(2);
        Plot.add("lines", b_values_x, b_values_y);
        Plot.add("circles", b_values_x, b_values_y);
        Plot.show;

//make an image
		selectWindow("Mother "+mother_numbers[i]+" + daughters a + b");
   		run("Select All");	
		run("Copy");
		run("Close");
		run("Internal Clipboard");
		selectWindow("Clipboard");
		rename("Mother "+mother_numbers[i]+" + daughters a + b");     
	}
}

function list_no_repeats (table, heading) {
//Returns an array of the entries in a column without repeats to use as an index

//Check whether the table exists
	if (isOpen(table)) {

//get the entries in the column without repeats
		no_repeats = newArray(getResultString(heading, 0));

		for (i=0; i<nResults; i++) {
			occurence = getResultString(heading, i);
			for (j=0; j<no_repeats.length; j++) {
				if (occurence != no_repeats[j]) {
					flag = 0;
				} else {
						flag = 1;
					}
				}
			
			if (flag == 0) {
				occurence = getResultString(heading, i);
				no_repeats = Array.concat(no_repeats, occurence);	
			}
		}
	} else {
		Dialog.createNonBlocking("Error");
		Dialog.addMessage("No table with the title "+table+" found.");
		Dialog.show();
	}
	return no_repeats;
}

function addToArray(value, array, position) {
//allows one to update existing values in an array
//adds the value to the array at the specified position, expanding if necessary - returns the modified array
//From Richard Wheeler - http://www.richardwheeler.net/contentpages/text.php?gallery=ImageJ_Macros&file=Array_Tools&type=ijm
    
    if (position < lengthOf(array)) {
        array[position]=value;
    } else {
        temparray = newArray(position+1);
        for (i=0; i<lengthOf(array); i++) {
            temparray[i]=array[i];
        }
        temparray[position]=value;
        array=temparray;
    }
    return array;
}

function list_no_repeats_skip (table, heading, skip) {
//Returns an array of the entries in a column without repeats to use as an index

//make the no_repeats array
	no_repeats = newArray();

//Check whether the table exists
	if (isOpen(table)) {

//get the entries in the column without repeats
		
		var done = false; // used to prematurely terminate loop
		for (i=0; i<nResults && !done; i++) {
			if (getResult(skip,i) == 0) {
			no_repeats = Array.concat(no_repeats, getResultString(heading, i));
			done = true;
		} else {}
		}

//exit if there are no tracks to plot
		if (no_repeats.length < 1) {
			exit("There are no tracks that meet your criteria to plot");
		}

		
		for (i=0; i<nResults; i++) {
			occurence = getResultString(heading, i);
			skip_flag = getResultString(skip, i);
			
			for (j=0; j<no_repeats.length; j++) {
				if (occurence != no_repeats[j] && skip_flag == 0) {
					flag = 0;
				} else {
						flag = 1;
					}
				}
			
			if (flag == 0) {
				occurence = getResultString(heading, i);
				no_repeats = Array.concat(no_repeats, occurence);	
			}
		}
	} else {
		Dialog.createNonBlocking("Error");
		Dialog.addMessage("No table with the title "+table+" found.");
		Dialog.show();
	}
	return no_repeats;
}
